#!/bin/bash
# lessteebag: perform a "less" on the most recent file in directory ~/Teebags

teebagDirectory=~/Teebags
usage() { echo "Usage: $0 [-[1-9]]" 1>&2; echo "Perform less on most recent file in ${teebagDirectory}"; exit 1; }

headParm=1
while getopts "123456789" opt; do
    case "${opt}" in 
        [1-9])
            headParm=${opt}
            ;;
        *)
            usage
            ;;
    esac
done
less ${teebagDirectory}/$(ls -t ${teebagDirectory} | head -${headParm} | tail -1)
