#!/bin/bash
# teebag: save input to a file in a directory using pwd
# Common usage: "cmd 2>&1 | teebag
# Saves a file in ${bagDirectory} (default: ~/TeeBags) with a file name 
# in format <datetime>_[optionalContext]_<pwdWhenRun>.txt

usage() { echo "Usage: $0 [-c <cmdWhoseOutputIsBeingTeed>]" 1>&2; exit 1; }

teedCmd=""
while getopts "c:" opt; do
    case "${opt}" in
        c)
            teedCmd=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
	    
teebagDirectory=~/Teebags
if [ ! -d ${teebagDirectory} ]; then
    mkdir ${teebagDirectory}
    echo "First teebag use: created ${teebagDirectory}"
fi
pwd=$(pwd)
dateTime=$(date "+%Y-%m-%dT%H:%M:%S")
pwdAsString=${pwd//\//_}
copyFileName=${dateTime}
if [ ! -z "${teedCmd}" ]; then
    copyFileName=${copyFileName}_${teedCmd}
fi
copyFileName=${copyFileName}${pwdAsString}.txt
copyPath=${teebagDirectory}/${copyFileName}
if [ ! -d ${teebagDirectory} ]; then
    echo "'Bag' directory '${teebagDirectory}' does not exist"
    exit 1
fi
touch copyPath
tee $copyPath
echo "teebag: Saved a copy of stdout to $copyPath"
