" _vimrc configuration file of Jim Stearns

""""
" Command copied from bin/exrc. ~/.exrc may not be pulled in by all vi flavors.
"
" Set vi to use "tab" key to generate 4 spaces.
" Justification: Python PEP-8 so recommends. Discussion at:
" http://stackoverflow.com/questions/120926/why-does-python-pep-8-strongly-recommend-spaces-over-tabs-for-indentation
" This can get more sophisticated. See http://stackoverflow.com/questions/69998/tabs-and-spaces-in-vim.
set noautoindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
" Show matching brace, paren, bracket
set showmatch
" Don't set wrap margin
" (set to 4 to get automatic newline nearfrom right edge of window.)
set wrapmargin=0
" Set line ending to unix \n not \r\n
set fileformat=unix

""""
" =====================
" Sourcing of external plugins
" =====================
" ym/yd/YM/YD commands:
source ~/bin/vim/BetterVim_examples/plugins/yankmatches.vim

" =====================
" Individual Commands
" =====================
"
" (No:Display line numbers on the left:)
""set number

" Or not: display current line number in the ruler line:
set ruler

" Conway recommendation: "watchdog" plugin for status line.

" Change the leave-insert-mode key (default is Esc)
inoremap jk <ESC>

" Remap the leader key from backslash to space key:
let mapleader = "\<Space>"

" Not here, but in OS: consider remapping CAPSLOCK to Cntl.

filetype plugin indent on
syntax on
set encoding=utf-8

" Windows-specific (behavior on Mac/Linux not yet determined):
" Use system clipboard for all yanking/deleting operations
" For more details, see:
" http://stackoverflow.com/questions/11489428/how-to-make-vim-paste-from-and-copy-to-systems-clipboard
set clipboard=unnamed

" Allow cntl-c/cntl-v to be copy/paste on Windows:
" (and does other stuff as well, TBD)
if has('win32')
	source $VIMRUNTIME/mswin.vim
endif

" From Damian Conway O'Reilly "Mastering Vim" video:
" Turn on highlighting in search:
set hlsearch
" To turn off the last search's highlighting, the command is:
" :nohlsearch
" Damiam suggests mapping backspace in normal mode to turn off highlighting:
nmap <silent> <BS> :nohlsearch<CR>

